version: "3.9"

# //1.- Define the reusable named volumes that persist important data between container restarts.
volumes:
  postgres_data:

# //2.- Configure a private network so the containers can communicate securely by service name.
networks:
  yamato:
    driver: bridge

services:
  # //3.- PHP-FPM application container that runs the Laravel codebase.
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: yamato-php
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      # //4.- Expose sensible defaults when the env file is missing (useful for CI scenarios).
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8080}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_CONNECTION: pgsql
      DB_DATABASE: ${DB_DATABASE:-yamato}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      REDIS_HOST: redis
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-database}
    volumes:
      # //5.- Mount the application source so local edits are reflected inside the container.
      - ./:/var/www/html
      # //6.- Cache Composer files to avoid repeated downloads during rebuilds.
      - ~/.composer:/tmp/composer-cache
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - yamato

  # //7.- Nginx frontend proxy that serves HTTP traffic and forwards PHP requests to the app container.
  web:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - yamato

  # //8.- Postgres database service that stores the application data.
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-yamato}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    healthcheck:
      # //9.- Wait for Postgres to accept connections before the PHP container boots.
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE:-yamato} -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - yamato

  # //10.- Redis in-memory store used for caching and queues.
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - yamato

  # //11.- Mailpit captures outgoing emails for inspection during development.
  mailpit:
    image: axllent/mailpit:v1.15
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - yamato
